### PR TITLE
feature/github actions

### PR DESCRIPTION
**Pull request by dendisuhubdy**
- [x] Update rust.yml

### CODE REVIEW

**Review by DrSensor — APPROVED** [review]
Nice! Do you generate `rust.yml` from the wizard panel?

**Comment by Ujang360** [comment]
I think it's redundant because apparently, I can enable the GH Action for this repo

**Comment by dendisuhubdy** [comment]
@DrSensor :joy: exactly

**Comment by dendisuhubdy** [comment]
@Ujang360 might be redundant. You guys can close this PR if so

**Comment by Ujang360** [comment]
I'm closing this, but hey, all greeen!!!

:joy:

**Pull request closed without merging**
